# web/models/barranco.py
from mongoengine import Document, StringField, FloatField, IntField, URLField, ListField, EmbeddedDocumentField, EmbeddedDocument

class Barranco(Document):
    nombre = StringField(required=True, max_length=100)
    descripcion = StringField()
    periodo_descenso = StringField()
    dificultad = StringField(choices=('Fácil', 'Moderado', 'Difícil'))
    poblacion = StringField()
    wikiloc = URLField()
    longitud = FloatField()
    altitud_max = FloatField()
    altitud_min = FloatField()
    diferencia = FloatField()
    rapeles = StringField()
    equipamiento = StringField()
    longitud_max = FloatField()
    cartografia = StringField()
    tiempo_recorrido = StringField()
    aproximacion = StringField()
    recorrido = StringField()
    retorno = StringField()
    topografia_imagen = URLField()
    descenso_info = StringField()
    meteorologia = StringField()
    caudal = StringField()
    rio = StringField()
    hilo_foro = URLField()
    punto_control_caudal = StringField()
    informacion_adicional = StringField()
    video_youtube = URLField()
    acceso_mapa_real = URLField()
    informacion_acceso = StringField()
    imagen_mapa_acceso = URLField()
    aproximacion_imagen_mapa = URLField()
    descenso_imagen_mapa = URLField()
    retorno_imagen_mapa = URLField()
    escapes = StringField()
    combinacion_barrancos = StringField()
    geomorfologia_hidrologia = StringField()
    observaciones = StringField()
    historia = StringField()

    def __str__(self):
        return self.descripcion
